server {
    listen 80;
    server_name localhost;
    index index.php index.html;
    root /workspace/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /workspace/public$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /workspace/public;
    }

    location ~ /\. {
        deny all;
    }
}